spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5434/customer
    username: customer_user
    password: customer_password

server:
  port: 8080

movie:
  service:
    url: http://localhost:7070